/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package browsebylineinjtable_j2sp0104;

import java.awt.Color;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PhongFPT
 */
public class TheView extends javax.swing.JFrame {

    /**
     * Creates new form TheView
     */
    
    public TheView() {
        initComponents();
        tblTable.setRowSelectionInterval(0, 0);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        btMoveFirst = new javax.swing.JButton();
        btMovePrevious = new javax.swing.JButton();
        btMoveNext = new javax.swing.JButton();
        btMoveLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Stock one", "No1-Washington street", "11/05/2010", null},
                {"2", "Stock two", "372 Cave town - 001 Banks", "09/07/2011", null},
                {"3", "Stock three", "Nary angel-890 Number one", "13/05/2010", null},
                {"4", "Stock four", "Twin tower - 01 Main street", "04/07/2015", null},
                {"5", "Stock five", "Victory anniversary", "08/12/2014", null}
            },
            new String [] {
                "StockID", "StokeName", "Address", "DateAvailable", "Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTable);

        btMoveFirst.setText("Move first");
        btMoveFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoveFirstActionPerformed(evt);
            }
        });

        btMovePrevious.setText("Move previous");
        btMovePrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMovePreviousActionPerformed(evt);
            }
        });

        btMoveNext.setText("Move next");
        btMoveNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoveNextActionPerformed(evt);
            }
        });

        btMoveLast.setText("Move Last");
        btMoveLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoveLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btMoveFirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMovePrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMoveNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMoveLast)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMoveFirst)
                    .addComponent(btMovePrevious)
                    .addComponent(btMoveNext)
                    .addComponent(btMoveLast))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMoveLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoveLastActionPerformed
        // TODO add your handling code here:
        tblTable.setRowSelectionInterval(tblTable.getRowCount()-1, tblTable.getRowCount()-1);
        btMoveNext.setEnabled(false);
        btMoveLast.setEnabled(false);
        btMovePrevious.setEnabled(true);
        btMoveFirst.setEnabled(true);
                
    }//GEN-LAST:event_btMoveLastActionPerformed

    private void btMoveFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoveFirstActionPerformed
        // TODO add your handling code here:
        tblTable.setRowSelectionInterval(0, 0);
        btMoveFirst.setEnabled(false);
        btMovePrevious.setEnabled(false);
        btMoveNext.setEnabled(true);
        btMoveLast.setEnabled(true);
    }//GEN-LAST:event_btMoveFirstActionPerformed

    private void btMovePreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMovePreviousActionPerformed
        // TODO add your handling code here:
        if(tblTable.getSelectedRow()>0){
            tblTable.setRowSelectionInterval(tblTable.getSelectedRow()-1, tblTable.getSelectedRow()-1);
            btMoveNext.setEnabled(true);
            btMoveLast.setEnabled(true); 
        }else{
            btMovePrevious.setEnabled(false);
            btMoveFirst.setEnabled(false);
        }
    }//GEN-LAST:event_btMovePreviousActionPerformed

    private void btMoveNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoveNextActionPerformed
        // TODO add your handling code here:
        //if selected-row position is not in the last position
        //select the next row
        if(tblTable.getSelectedRow()<tblTable.getRowCount()-1){
            tblTable.setRowSelectionInterval(tblTable.getSelectedRow()+1, tblTable.getSelectedRow()+1);
            btMovePrevious.setEnabled(true);
            btMoveFirst.setEnabled(true);
        }else{
       //     tblTable.getSelectionModel().clearSelection();    
            btMoveNext.setEnabled(false);
            btMoveLast.setEnabled(false);
                   
        }
    }//GEN-LAST:event_btMoveNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMoveFirst;
    private javax.swing.JButton btMoveLast;
    private javax.swing.JButton btMoveNext;
    private javax.swing.JButton btMovePrevious;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTable;
    // End of variables declaration//GEN-END:variables
}
